# -*- coding: utf-8 -*-
import contextlib
# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code_fo generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import shutil
import subprocess
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import qdarkstyle
import time
from PyQt5.QtSql import *
import Camera
from alterDialog import alterPaDialog
from PyQt5 import QtCore, QtGui, QtWidgets
from alterDialog import *
from code_fo import alterDialog_beifen
from indexres import *
import os
from datetime import time

from PyQt5 import QtWidgets, QtGui
from PyQt5.QtCore import *
from PyQt5.QtSql import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from tqdm import tk
# from untitled import *
from addDialog import addPaDialog
from alterDialog import alterPaDialog
# from untitled import Ui_MainWindow
import sys, sqlite3
from PyQt5.QtGui import QIcon, QPixmap
from indexres import *
from image import *

class Ui_MainWindow(QDialog):
    # add_pa_success_signal = pyqtSignal()

    a = 0
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.setupUi()

        # 设置软件图标
        # self.setWindowIcon(QtGui.QIcon("icon.ico"))
        #         self.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
        # "    border-top-left-radius:10px;\n"
        # "    border-top-right-radius:10px;\n"
        # "}")
        # self.init_widget()
        self.setWindowModality(Qt.WindowModal)
        self.setWindowTitle("患者信息")
        self.save_clicked = False  # 添加一个布尔型变量

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(674, 416)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 674, 416))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 631, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(460, 0, 161, 31))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(50, 5, 51, 27))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"     padding-bottom:3px\n"
"}")
        self.pushButton.setObjectName("pushButton_3")
        self.pushButton.setParent(self)
        self.pushButton.setCheckable(True)
        self.pushButton.clicked.connect(self.slot_a4)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_3")
        self.pushButton_2.setParent(self)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.clicked.connect(self.slot_a4)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 5, 51, 27))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                      "    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
                                      "\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "     padding-bottom:3px\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(104, 5, 51, 27))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"}\n"
"QPushButton:hover{\n"
"     padding-bottom:3px\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/cha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         self.pushButton_2.setIcon(icon)
#         self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
#         self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(70, 10, 71, 21))
        self.label.setStyleSheet("font: 12pt \"华文仿宋\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 21, 21))
        self.label_2.setStyleSheet("border-image: url(:/images/touxiang2.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(9, 49, 111, 271))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"     padding-bottom:3px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/touxiang.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 50, 51, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setParent(self)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.clicked.connect(self.slot_a1)
        # self.hLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"  \n"
"}\n"
"QPushButton:hover{\n"
"     padding-bottom:3px\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("indexres/yinpin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setObjectName("pushButton_3")
        self.pushButton_4.setParent(self)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.clicked.connect(self.slot_a2)
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"  \n"
"}\n"
"QPushButton:hover{\n"
"     padding-bottom:3px\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("indexres/paizhao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setObjectName("pushButton_3")
        self.pushButton_5.setParent(self)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.clicked.connect(self.slot_a3)
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"  \n"
"}\n"
"QPushButton:hover{\n"
"     padding-bottom:3px\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/dianji.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(139, 65, 481, 271))
        self.frame_6.setStyleSheet("\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(202, 232, 164, 202), stop:1 rgba(255, 238, 112, 169));\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(10, 10, 461, 251))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
#         self.label_3 = QtWidgets.QLabel(self.frame_7)
#         self.label_3.setGeometry(QtCore.QRect(30, 20, 61, 31))
#         self.label_3.setStyleSheet("font: 12pt \"宋体\";\n"
# "color:rgb(89, 89, 89);\n"
# "")
#         self.label_3.setObjectName("label_3")
#         self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
#         self.lineEdit.setGeometry(QtCore.QRect(80, 30, 121, 21))
#         self.lineEdit.setStyleSheet("border:none;\n"
# "border-bottom:1px solid rgb(186, 180, 180);\n"
# "border-radius:0px")
#         self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.frame_3)
        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")

        self.temp_alter_no = "11"
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        # self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)






    def slot_a1(self):
        from t_main import IndexWindow
        # addDialog = alterPaDialog(self)
        # # addDialog.add_pa_success_signal.connect(self.window.searchButtonClicked)
        # addDialog.show()
        # addDialog.exec_()
        # IndexWindow.searchButtonClicked()
        IndexWindow.boby2()

       # IndexWindow.db = QSqlDatabase.addDatabase("QSQLITE")
       # IndexWindow.db.setDatabaseName('database.db')
       # IndexWindow.db.open()
       # IndexWindow.tableView = QTableView()
       # IndexWindow.tableView.setSelectionBehavior(QAbstractItemView.SelectRows)  # 设置只能选中整行
       # IndexWindow.tableView.setSelectionMode(QAbstractItemView.SingleSelection)  # 设置只能选中一行
       # IndexWindow.func_mappingSignal()
       # # self.showPaImage()
       # index = IndexWindow.tableView.currentIndex()  # 取得当前选中行的index
       # from alterDialog import alterPaDialog
       # dialog = alterPaDialog()
       # IndexWindow.dialog.setNo(IndexWindow.temp_pano)
       # self.alterDialog.fillContent()
       # self.alterDialog.show()
       # self.alterDialog.exec_()
       # self.searchButtonClicked()




    def slot_a2(self):
        # from standard_audio import StandardAudioRecorder
        import standard_audio
        self.one = standard_audio.StandardAudioRecorder()
        self.one.show()

    def slot_a3(self):
        import Camera
        self.one = Camera.CameraWindow()
        self.one.show()
    def slot_a4(self):
        print("helloa")




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "信息查询与修改"))
        # self.pushButton.setText(_translate("MainWindow", "➖"))
        # self.pushButton_2.setText(_translate("MainWindow", "×"))
        self.label.setText(_translate("MainWindow", "信息"))
        self.pushButton_3.setText(_translate("MainWindow", "患者信息"))
        self.pushButton_4.setText(_translate("MainWindow", "录 音"))
        self.pushButton_5.setText(_translate("MainWindow", "拍 照"))
        self.pushButton_8.setText(_translate("MainWindow", "教 程"))
        # self.label_3.setText(_translate("MainWindow", "姓名："))
        self.menu.setTitle(_translate("MainWindow", "欢迎使用康复训练系统"))
import indexres
if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon("./images/MainWindow_1.png"))
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    mainMindow = Ui_MainWindow()
    mainMindow.show()
    sys.exit(app.exec_())